version: '3'
services:
  backend:
    container_name: backend
    build: ./backend
    expose:
      - "5000"
    ports:
      - "5000:5000"
  frontend:
    container_name: frontend
    build: ./frontend
    expose:
      - "4200"
    ports:
      - "4200:4200"
    depends_on:
      - backend
